Update dropdown attribute
Tech-Fabric/CloudFabric.EAV pull request #47
Opened 2023-01-11 11:48 UTC by scand1n

2023-01-11 11:56 UTC, dgon-jd requested changes

2023-01-11 11:56 UTC, dgon-jd commented on CloudFabric.EAV.Domain/Models/Attributes/ValueFromListAttributeConfiguration.cs
> +            if (instance == null)
The 'null-check' is included in the `base.Validate()` and it throws error only if the `if (IsRequired && instance == null)` so there is no point in this here

2023-01-11 12:15 UTC, ustims approved these changes

2023-01-12 11:07 UTC, maxxsem commented on CloudFabric.EAV.Tests/Tests.cs
> +
Do we need to call CreateEntityConfiguration() here again?

2023-01-12 11:10 UTC, maxxsem commented on CloudFabric.EAV.Domain/Models/Attributes/ValueFromListAttributeConfiguration.cs
> +                errors.Add("Cannot validate attribute. Expected attribute type: Dropdown");
Do we have a Dropdown type in our library?
Maybe it's more clear to use ValueFromList?

2023-01-12 11:43 UTC, scand1n commented on CloudFabric.EAV.Tests/Tests.cs
> +
yes, it checks another case with repeated names

2023-01-12 15:54 UTC, merged