{{WIP}} CategoryTree, Categories and Paths
Tech-Fabric/CloudFabric.EAV pull request #63
Opened 2023-01-31 23:21 UTC by dgon-jd

2023-02-25 22:18 UTC, ustims requested changes

2023-02-25 22:18 UTC, ustims commented on CloudFabric.EAV.Tests/EntityInstanceQueryingTests.cs
> +        var instance12 = instance1.Children.FirstOrDefault(x => x.Id == createdCategory12.Id);
Please give those instances better names, it's really hard to follow. Something from real world, ecommerce examples will work, like Computers->Laptops|Desktops->PC|Mac

2023-02-25 22:18 UTC, ustims commented on CloudFabric.EAV.Tests/EntityInstanceQueryingTests.cs
> +public enum ProjectionStorageType
There is no need to use such enum. There is a test class for every storage implementation, you can simply override test method there and add [Ignore] attribute

2023-02-25 22:18 UTC, ustims commented on CloudFabric.EAV.Tests/Tests.cs
> -using System.Globalization;
Could you please make your changes in such a way that does not overwrite whole file history?

2023-02-27 13:29 UTC, ustims requested changes

2023-02-27 13:29 UTC, ustims commented on CloudFabric.EAV.Tests/EntityInstanceQueryingTests.cs
> +// ReSharper disable AsyncConverter.ConfigureAwaitHighlighting
Please move category tests out to a new file

2023-02-27 13:47 UTC, ustims commented on CloudFabric.EAV.Service/EAVService.cs
> +    public async Task<(EntityInstanceViewModel, ProblemDetails)> MoveItemAsync(Guid itemId, string itemPartitionKey, Guid treeId, Guid newParentId, CancellationToken cancellationToken)
`Move` is too wide and does not include anything related to categories. And for PIM, moving can mean a lot - moving between warehouses for example. Let's just say UpdateCategoryPath.

2023-02-27 15:12 UTC, dgon-jd commented on CloudFabric.EAV.Tests/EntityInstanceQueryingTests.cs
> +        var instance12 = instance1.Children.FirstOrDefault(x => x.Id == createdCategory12.Id);
Changed to the laptops example

2023-02-27 15:12 UTC, dgon-jd commented on CloudFabric.EAV.Tests/EntityInstanceQueryingTests.cs
> +public enum ProjectionStorageType
Done

2023-02-27 15:14 UTC, dgon-jd commented on CloudFabric.EAV.Service/EAVService.cs
> +    public async Task<(EntityInstanceViewModel, ProblemDetails)> MoveItemAsync(Guid itemId, string itemPartitionKey, Guid treeId, Guid newParentId, CancellationToken cancellationToken)
Renamed

2023-02-27 16:26 UTC, dgon-jd commented on CloudFabric.EAV.Tests/Tests.cs
> -using System.Globalization;
Reverted to LF line endings

2023-02-27 16:26 UTC, dgon-jd commented on CloudFabric.EAV.Tests/EntityInstanceQueryingTests.cs
> +// ReSharper disable AsyncConverter.ConfigureAwaitHighlighting
Moved to a separate test file

2023-02-28 15:45 UTC, ustims approved these changes

2023-03-01 11:47 UTC, merged