feat(updateInstance): Moved attributes for remove to a separate param
Tech-Fabric/CloudFabric.EAV pull request #82
Opened 2023-04-03 13:06 UTC by dgon-jd

2023-04-07 10:43 UTC, ustims requested changes

2023-04-07 10:43 UTC, ustims commented on CloudFabric.EAV.Models/RequestModels/EntityInstanceUpdateRequest.cs
> +    public List<string>? AttributesMachineNamesToRemove { get; set; }
I just confirmed with Julia that it's better to use AttributeMachineNames (without s)

2023-04-07 11:11 UTC, dgon-jd commented on CloudFabric.EAV.Models/RequestModels/EntityInstanceUpdateRequest.cs
> +    public List<string>? AttributesMachineNamesToRemove { get; set; }
Renamed

2023-04-10 15:17 UTC, ustims approved these changes

2023-04-10 18:26 UTC, merged