Added methods to create categories with json arguments
Tech-Fabric/CloudFabric.EAV pull request #83
Opened 2023-04-04 08:58 UTC by scand1n

2023-04-04 09:29 UTC, scand1n commented
update build.yml

2023-04-05 14:08 UTC, scand1n commented on CloudFabric.EAV.Service/EAVService.cs
>      public async Task<(CategoryViewModel, ProblemDetails)> CreateCategoryInstanceAsync(
Remove "Async" from method naming

2023-04-07 09:56 UTC, ustims requested changes

2023-04-07 09:56 UTC, ustims commented on CloudFabric.EAV.Service/EAVService.cs
> +)
Bad formatting

2023-04-07 09:56 UTC, ustims commented on CloudFabric.EAV.Service/EAVService.cs
> +    /// ```
\`\`\` should be moved above the comment to only include json in \`\`\`... \`\`\` section

2023-04-07 09:56 UTC, ustims commented on CloudFabric.EAV.Service/EAVService.cs
> +    /// ```
\`\`\` should be moved above the comment to only include json in \`\`\`... \`\`\` section

2023-04-07 09:56 UTC, ustims commented on CloudFabric.EAV.Service/EAVService.cs
> +    /// ```
\`\`\` should be moved above the comment to only include json in \`\`\`... \`\`\` section

2023-04-07 09:56 UTC, ustims commented on CloudFabric.EAV.Tests/JsonSerializationTests.cs
> +        JsonSerializerOptions _serializerOptions = new JsonSerializerOptions();
I believe there is an options instance somewhere in tests which is passed to eav service. Is it possible to use that one?

2023-04-07 11:02 UTC, ustims approved these changes

2023-04-07 11:24 UTC, merged