Money type
Tech-Fabric/CloudFabric.EAV pull request #85
Opened 2023-04-06 12:45 UTC by dgon-jd

Added money attribute. 
Config: 
- receives list of currencies. If empty, uses default hardcoded list
- receives default currency id for this attribute

instance: 
- receives value

2023-04-06 13:57 UTC, ustims requested changes

2023-04-06 13:57 UTC, ustims commented on CloudFabric.EAV.Domain/Models/Attributes/Currency.cs
> +public class Currency
https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/records

and 

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#value-equality

I suppose that will remove the need for overriding Equals and other methods

2023-04-10 18:37 UTC, dgon-jd commented on CloudFabric.EAV.Tests/Tests.cs
> +        ProjectionQueryResult<AttributeConfigurationListItemViewModel> allAttributes =
This is a copy-paste from many other similar tests. What is the problem specifically?

2023-04-10 18:37 UTC, dgon-jd commented on CloudFabric.EAV.Domain/Models/Attributes/Currency.cs
> +public class Currency
Make sense. Changed to a record.

2023-04-10 18:40 UTC, dgon-jd commented on CloudFabric.EAV.Domain/Models/Attributes/MoneyAttributeConfiguration.cs
> +        if (moneyInstance.Value < 0)
Removed

2023-04-11 12:30 UTC, ustims approved these changes

2023-04-11 14:01 UTC, ustims commented on CloudFabric.EAV.Domain/Models/Attributes/MoneyAttributeConfiguration.cs
> +    private List<Currency> DefaultListOfCurrencies() => new List<Currency>
Where's bitcoin? 🪙

2023-04-11 14:03 UTC, ustims commented on CloudFabric.EAV.Domain/Models/Attributes/MoneyAttributeConfiguration.cs
> +    public override bool Equals(object obj)
Do we still need those methods after switching to record?

2023-04-11 14:05 UTC, ustims commented on CloudFabric.EAV.Tests/Tests.cs
> +        ProjectionQueryResult<AttributeConfigurationListItemViewModel> allAttributes =
maybe this runs on InMemory/Postgresql synchronous repositories. It's okay, I just noticed that there is no wait for projections, after creating an entity config it immediately queries them

2023-04-18 12:12 UTC, merged